# Generated by Django 2.2 on 2022-03-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='hobby_image',
            field=models.CharField(default='https://cdn.iconscout.com/icon/premium/png-256-thumb/hobby-6-1100854.png', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.CharField(default='https://cdn.iconscout.com/icon/premium/png-256-thumb/notebook-1717991-1459674.png', max_length=500),
        ),
    ]
